### ISSUE TITLE
[Improvement]: Address ArcticSourceTest blocking problems

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/arctic#1230]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

1. add a timeout strategy to collect the records from an unbounded stream.
2. locate the method and figure out why this collecting job is always running.
3. add logs to help address it.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [x] #1231 @YesOrNo828 
- [x] #1241 @YesOrNo828 
- [x] #1254  @YesOrNo828 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
