### ISSUE TITLE
[Improvement]: AMS module refactoring in 0.5

### ISSUE THREAD

**Issue by majin1102** [NetEase/arctic#1372]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

AMS Refactoring Goals:

1. More elegant module designing, such as merging optimizer module into ams module and unifying ams-related interfaces into ams-api.
2. More elegant interface abstraction, reorganizing modules and implementations around table service and optimizing service.
3. Unify optimizing planning logics for mixed format and native Iceberg format, with mixed format planning inheriting from native Iceberg.
4. Abstract resource type to prepare for providing more plugin functionality in the future.
5. Optimize optimizer code logic to prepare for extending more table formats in the future.
6. Improve code simplicity and readability, especially for system database operations.
7. Optimize optimizing service interface and provide standardized exception codes.
8. More refactoring work oriented towards future expansion…

Compatibility:
- Table service interfaces are compatible, which means flink, spark, and trino interfaces are compatible.
- Optimizer interfaces are not compatible and require clearing all optimizers and restarting.

### How should we improve?

This issue and PR would be a total refactoring for ams.This work would be mainly followed by me, @zhoujinsong @hameizi @shidayang 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [ ] #1411 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
