### ISSUE TITLE
[Improvement]: Add a new template with SUBTASK in the Arctic Issues

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/arctic#406]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?page=4&q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I want to add a new template with SUBTASK in the Arctic Issues. So we can create an umbrella feature or improvement that includes a range of subtasks.

### How should we improve?

Create a new template in the path: `.github/ISSUE_TEMPLATE`.

Modified the `[feature_request.yml]` and `[improvement.yml]`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
