### ISSUE TITLE
[Improvement]: update site docs for 0.4 version

### ISSUE THREAD

**Issue by majin1102** [NetEase/arctic#761]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

update site docs for 0.4 version，and the outline should be like this:
![image](https://user-images.githubusercontent.com/5731171/204248804-57db2221-859d-405e-a44e-fca129ea128f.png)

### How should we improve?

this is a top issue for 0.4 docs improvement

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [x] #788 
- [x] #831

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
